[tool.ruff]
line-length = 140
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 140

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "proj3ct.settings"
python_files = "test_*.py"
minversion = "7.4.0"
pythonpath = "."
addopts = "-raP -q -s -x -vv --doctest-modules --disable-pytest-warnings --no-cov-on-fail --cov=proj3ct --cov-report=term-missing --cov-report=html:coverage"

[tool.coverage.report]
skip_empty = true
source = "proj3ct/**/*.py"
omit = ["proj3ct/**/migrations/*.py", "proj3ct/settings.py", "proj3ct/asgi.py", "proj3ct/wsgi.py", "proj3ct/urls.py"]

[tool.taskipy.tasks]
lint = 'black . --check --diff'
format = 'isort . &&  && black .'
run = 'python manage.py runserver --insecure'
migrate = 'python manage.py migrate'
migrations = 'python manage.py makemigrations'
shell = 'python manage.py shell_plus --ipython -- --profile=recipes'
pre_test = 'task lint'
test = 'pytest'
