[tool.ruff]
line-length = 140
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 140

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "proj3ct.settings"
python_files = "test_*.py"
minversion = "7.4.0"
pythonpath = "."
addopts = """
    -ra -q -s -x -vvv \
    --doctest-modules \
    --disable-pytest-warnings \
    --cov=proj3ct \
    --cov-report=html:coverage
    """

[tool.coverage.report]
skip_empty = true
branch = true
source = "proj3ct/**/*.py"
omit = [
    "proj3ct/**/migrations/*.py",
    "proj3ct/*.py",
    "proj3ct/**/populate_recipes.py",
    "proj3ct/**/factory.py"
]

[tool.taskipy.tasks]
lint = 'black . --check --diff'
format = 'isort . &&  && black .'
run = 'python manage.py runserver --insecure'
migrate = 'python manage.py migrate'
migrations = 'python manage.py makemigrations'
shell = 'python manage.py shell_plus --ipython -- --profile=recipes'
pre_test = 'task lint'
test = 'pytest'
