[tool.ruff]
line-length = 140
exclude = ['.venv', 'migrations']

[tool.isort]
profile = "black"
line_length = 140

[tool.pytest.ini_options]
minversion = "7.4.0"
pythonpath = "."
addopts = "-ra -q -s -x -vv --disable-pytest-warnings --cov=proj3ct --cov-report=term-missing --cov-report=html"

[tool.coverage.report]
skip_empty = true
source = "proj3ct/**/*.py"
omit = ["proj3ct/**/migrations/*.py", "proj3ct/settings.py", "proj3ct/asgi.py", "proj3ct/wsgi.py", "proj3ct/urls.py"]

[tool.taskipy.tasks]
lint = 'ruff . && blue --check . --diff'
format = 'isort . && ruff . && blue .'
run = 'python manage.py runserver'
migrate = 'python manage.py migrate'
makemigrations = 'python manage.py makemigrations'
shell = 'python manage.py shellplus'
pre_test = 'task lint'
test = 'pytest'
post_test = 'coverage html'
