[tool.ruff]
line-length = 140
exclude = ['.venv', 'venv', 'migrations']
target-version = "py311"

[tool.ruff.mccabe]
max-complexity = 10

[tool.isort]
profile = "black"
line_length = 140

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "proj3ct.settings"
python_files = "test_*.py"
minversion = "7.4.0"
pythonpath = "."
addopts = """
    -ra -q -s -x -vvv \
    --doctest-modules \
    --disable-pytest-warnings \
    --cov=proj3ct \
    --cov-report=html:coverage
    """

[tool.coverage.report]
skip_empty = true
branch = true
source = "proj3ct/**/*.py"
omit = [
    "proj3ct/**/migrations/*.py",
    "proj3ct/*.py",
    "proj3ct/**/populate_recipes.py",
    "proj3ct/**/factory.py"
]

[tool.taskipy.tasks]
lint = 'make lint'
format = 'make format'
run = 'make run'
migrate = 'make migrate'
migrations = 'make migrations'
shell = 'make shell'
pre_test = 'make lint'
test = 'make test'
